---
title: "Group_last"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    code_folding: show
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r libraries}
library(tidyverse)
library(zoo)
library(devtools)
library(roxygen2)
library(testthat)
library(knitr)
```

```{r}
swiss_df <- read.csv("data/SwissCities.csv" , stringsAsFactors = FALSE,fileEncoding = "UTF-8-BOM"
)
swiss_df
```

```{r}
names(swiss_df) <- tolower(names(swiss_df))
names(swiss_df) <- gsub(" ", "_", names(swiss_df))

# remove duplicated rows
swiss_df <- unique(swiss_df)

# Convert numeric columns
if ("latitude" %in% names(swiss_df)) {
  swiss_df$latitude <- as.numeric(swiss_df$latitude)
}

if ("longitude" %in% names(swiss_df)) {
  swiss_df$longitude <- as.numeric(swiss_df$longitude)
}

if ("population" %in% names(swiss_df)) {
  swiss_df$population <- as.numeric(swiss_df$population)
}
swiss_df <- swiss_df[rowSums(is.na(swiss_df) | swiss_df == "") < ncol(swiss_df), ]


# show data
head(swiss_df)
```

```{r}
#' Build route query table
#'
#' Creates a table with all origin-destination-date-time combinations.
#'
#' @param station_data Data frame returned by read_station_data().
#' @param group_id_value Group ID to filter, for example 4.
#' @param query_date Selected query date.
#' @param query_times Selected query times.
#'
#' @return A data frame with route queries.
#' @export
build_route_query_table <- function(station_data,
                                    group_id_value = 4,
                                    query_date = "2025-06-20",
                                    query_times = c("07:30", "09:00", "12:00", "17:00", "19:00")) {
  
  group_data <- station_data[station_data$group_id == group_id_value, ]
  
  origin <- group_data[group_data$is_origin == TRUE, ]
  destinations <- group_data[group_data$is_origin == FALSE, ]
  
  query_table <- data.frame(
    group_id = destinations$group_id,
    region = destinations$region,
    from_city = origin$city,
    to_city = destinations$city,
    from_station_id = origin$station_id,
    to_station_id = destinations$station_id
  )
  
  query_table <- merge(
    query_table,
    data.frame(query_date = query_date, query_time = query_times)
  )
  
  return(query_table)
}

```

```{r}


query_table <- build_route_query_table(
  station_data = swiss_df,
  group_id_value = 4,
  query_date = "2025-06-20",
  query_times = c("07:30", "09:00", "12:00", "17:00", "19:00")
)

query_table
```

```{origin_station <-swiss_df %>%}
  filter("region")
```
